@baseUrl = http://localhost:8000/api

# health check
GET {{baseUrl}}/health

###

GET {{baseUrl}}/users

###

# ログイン
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "legacy.app@example.com",
  "password": "P@ssw0rd"
}

###
# 登録
POST {{baseUrl}}/register
Content-Type: application/json

{
  "name": "legacy5",
  "email": "legacy.app5@example.com",
  "password": "P@ssw0rd"
}

###
# ニュース一覧
GET {{baseUrl}}/v1/news
Accept: application/json
Origin: http://localhost:8000
